gpu_id: 2
multi_gpus: False
num_workers: 4
mode: 'sgdet'
transformer_mode: 'img'

optimizer: 'adamw'
lr: 0.00001
nepoch: 5
enc_layer: 1
dec_layer: 3
bce_loss: True
is_wks: True
feat_dim: 2048
pseudo_way: 0
remove_one_frame_video: False
union_box_feature: True

save_path: 'models/oneframe/'
model_path: 'models/oneframe/model_4.tar'
data_path: '/home/csq/datasets/ActionGenome/dataset/ag/'
datasize: 'large'
ckpt: None
ws_object_bbox_path: 'annotations/gt_annotation_thres02_keep1.pkl'
